development:
  adapter: postgresql
  database: cards_development
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: cards_test
  encoding: unicode
  pool: 5
  host: localhost
  min_messages: warning
